### ISSUE TITLE
Inaccurate information: The explicit pattern 'E' will print only 'Tue' instead of 'Tuesday'

### ISSUE THREAD

**Issue by prasadsunny1** [dart-lang/i18n#113]
The table shows explicit patterns in DateFormat Class's documentation on `https://api.flutter.dev/flutter/intl/DateFormat-class.html` seems inaccurate.

According to the table `DateFormat('E').format(DateTime.now())` will return a full word of the day name. for eg. `Tuesday`

But When I try it in my code, it returns the short name of the day `Tue`

This is the reference to documentation:
https://github.com/dart-lang/intl/blob/3d12bf16b87208d879ba31cc3961f5c1cf42b810/lib/src/intl/date_format.dart#L163

Is this correct behaviour or should I update this documentation?

**Comment by timsneath** [comment]
`EEEE` is the right format for the full day (e.g. "Tuesday"), `EEE` is the format for an abbreviated day (e.g. "Tue").

This is covered in the documentation under the subheading "Text":
https://api.flutter.dev/flutter/intl/DateFormat-class.html#:~:text=The%20count%20of%20pattern%20letters,numeric%20form%20if%20one%20exists

What change would you propose to the documentation?

**Comment by prasadsunny1** [comment]
I raised this issue 2y ago when I had started learning flutter and the issue does not make any sense anymore.
So, let's close this issue
