### ISSUE TITLE
Add format for narrow week days

### ISSUE THREAD

**Issue by ghost** [dart-lang/i18n#176]
It seems that the `DateFormat` class does not support narrow week days.

Reference: 
[intl/lib/src/data/dates/symbols/en_US.json](https://github.com/dart-lang/intl/blob/master/lib/src/data/dates/symbols/en_US.json)

```
"NARROWWEEKDAYS":["S","M","T","W","T","F","S"],
"STANDALONENARROWWEEKDAYS":["S","M","T","W","T","F","S"]
```

**Comment by cleong98** [comment]
Hi Hi,  about this have any update? if haven't update can i doing some change and pr this?

**Comment by mosuem** [comment]
Does #703 address your issue @cleong98?

**Comment by cleong98** [comment]
I think yes, this feature will release in next version? @mosuem
