### ISSUE TITLE
NumberFormat should have tryParse

### ISSUE THREAD

**Issue by kentcb** [dart-lang/i18n#191]
`NumberFormat` does not currently include a `tryParse` implementation, meaning client code can only use `parse` in combination with `try`/`catch`. This is particularly annoying when running with break-on-all-exceptions enabled.

`NumberFormat` should implement the same `tryParse` pattern as elsewhere in the Dart SDK.

**Comment by bartekpacia** [comment]
Should this be closed now that these changes are merged to mainline?

**Comment by utamori** [comment]
@mosuem
this issue appears to be resolved.
