### ISSUE TITLE
Dateformat not parsing after a format generated string

### ISSUE THREAD

**Issue by rmarau** [dart-lang/i18n#211]
Given this `"yyyyMMddHHmmss"` format:
`DateFormat("yyyyMMddHHmmss").format(DateTime.now());` gives a nice string like: `"20190405140723"` as I would expect.

Now reversely parsing...
`DateFormat("yyyyMMddHHmmss").parse("20190405140723");` throws the message "Trying to read MM from 20190405140723 at position 14"

It seems the parser consumes the whole string (after the 2019) while searching for some separator that I don't have in the format.

Shouldn't parse and format be reversible?

I've tried with parseLoose and parseStrict: same result.
Using intl version: "0.15.8"

**Comment by woprandi** [comment]
`FixedDateTimeFormatter` seems not able to handle 2-digit year as input
