### ISSUE TITLE
Allow making use of native JS Intl object if available

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/i18n#353]
If we're in most modern browsers (not Safari or IE10 yet) then there's an Intl namespace available with NumberFormat, DateFormat and Collation. We should look at exposing that functionality. We probably can't outright replace our own because we need something that will work outside the browser, has less less implementation variation, etc., but we should permit it, and exposing Collation would fill a big gap.

**Comment by mosuem** [comment]
Done with `package:intl4x`.
