### ISSUE TITLE
FormatException on specific date and time (very strange)

### ISSUE THREAD

**Issue by akhatriST** [dart-lang/i18n#483]
**Describe the bug**
Getting the following exception on this specific date range only i.e. **23-03-12 02:00:00** to **23-03-12 02:59:59** with the following message

_FormatException: Error parsing 23-03-12 02:00:00, invalid hour value: 2 in en_US with time zone offset -4:00:00.000000. Expected value between 3 and 3. Date parsed as 0023-03-12 03:00:00.000.._

**To Reproduce**
The timezone should be either UTC -4, -5, -6, -7 and running a local test as following will reproduce it. Please note that this works fine for all the time windows except **02:00:00 till 02:59:59** 
```
void main(List<String> arguments) {
    String date = "23-03-12 02:00:00";
    DateTime? dateTime = DateFormat('y-MM-dd HH:mm:ss').parseStrict(date).toLocal();
}
```

**Expected**
The library should work as expected on the above mentioned time range.

**Comment by slgobinath** [comment]
Facing the same error in Eastern Timezone. Any fix?
