### ISSUE TITLE
How to handle lot of files?

### ISSUE THREAD

**Issue by zreptil** [dart-lang/i18n#528]
I have a project that has lots of dart files in it. When running the commands generate_from_arb or extract_to_arb i have to specify each single file in the commandline. When using generate_from_arb i also have to provide every single arb file in the commandline to get a working messages_all.dart file containing every translation.

I call this by using a Windows DOS shell where the commandline is limited to 2047 chars. This limit can easily be exceeded by having a lot of dart files and a project-structure with some directory levels together with many languages. How can this be handled for big projects? Is there a way to use wildcards in the commandline or to call generate_from_arb multiple times without overwriting the results of earlier calls?

**Comment by gregory112** [comment]
@liudonghua123 Does this glob pattern include recursive subfolders though: `lib/**/*.dart`? It seems that it only scans `lib/folder1/*.dart` and `lib/folder2/*.dart` but not `lib/folder1/subfolder/*.dart`.
