### ISSUE TITLE
Incompatible Update of 'intl' Library in Flutter, Conflicting with 'timeago' 

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [dart-lang/i18n#646]
The specific problem arises when I try to update the intl library to a newer version. The updated version of intl library does not align with the version of the timeago library I currently have in my project. As a result, this creates a compatibility conflict between the two libraries.

The compatibility issue prevents me from benefiting from the improvements and bug fixes introduced in the updated intl library. It also limits my ability to utilize the latest features and enhancements available in the newer version.

When I attempt to update the intl library, I encounter error messages or warnings indicating the incompatibility between the intl and timeago libraries. These error messages may include version mismatch warnings, conflicting dependency errors, or runtime exceptions.

Current intl library version: 0.17.0
Current timeago library version: 3.3.0
Target intl library version: 0.18.1

**Comment by devoncarew** [comment]
I believe this is expected. If you're using Flutter, you essentially must use the exact version of package:intl that flutter uses (it pins package:intl to an exact version though package:flutter_localizations - https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml#L11).

What version of Flutter are you using?

If absolutely critical to rev to the latest version of intl, you can always use a dependency override in your pubspec, but the behavior after that (will flutter be happy w/ that version of the package? will other packages?) won't be well specified.

**Comment by devoncarew** [comment]
For other people who may see this issue, it would be useful to include the output of `flutter --version`; thanks!

**Comment by emanuelzallikodelabs** [comment]
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1


  Emanuel Zalli


+383 (0) 49 387 482

***@***.***

Emanuel Zalli <https://www.linkedin.com/in/emanuel-zalli-387788178/>

kodelabs.com

**Comment by mosuem** [comment]
Closed as this is expected and there is a fix in pinning the dependency.
