### ISSUE TITLE
My iOS app is not building after upgrading to Flutter 3.10 (intl ^0.18.1)

### ISSUE THREAD

**Issue by darrellbacarro** [dart-lang/i18n#647]
I am trying to run my app that uses intl for date and number formatting. I was able to run my app in android but it is not building for iOS.

Here's the debug console logs when building for iOS.
<img width="1157" alt="Screenshot 2023-05-12 at 4 14 56 PM" src="https://github.com/dart-lang/i18n/assets/4451999/0c39f16e-b38c-4115-87e8-2db01611175d">

Asking for some help to fix this. Thank you!

**Comment by mosuem** [comment]
I cannot reproduce this error, can you give more details how this occured?
