### ISSUE TITLE
DateFormat does not handle 12 PM / noon correctly

### ISSUE THREAD

**Issue by turboki** [dart-lang/i18n#668]
**Describe the bug**
Ran into a very strange bug recently where parsing a date time with any 12 PM timestamp ends up returning next day midnight. 
For example:
`6/10/2023 12:00 PM` ends up parsing as `2023-06-11 00:00:00.000`

Not only is the time parsed incorrectly, but the date is being incremented. Parse should not be incrementing at all. Is this a bug or am I missing something?

**To Reproduce**
Add a minimal working example or, if not possible or available, any code which might help to reproduce the problem
```
DateFormat("MM/dd/yyyy H:mm a").parse("6/10/2023 11:59 PM") // 2023-06-10 23:59:00.000 this correct!
DateFormat("MM/dd/yyyy H:mm a").parse("6/10/2023 12:00 PM") // 2023-06-11 00:00:00.000 this is WRONG
```

**System info**
- intl 0.18.1

**Comment by turboki** [comment]
Also 
`DateFormat("MM/dd/yyyy H:mm a").parse("6/10/2023 12:00 AM")` evaluates to `2023-06-11 12:00:00.000` which is also wrong

`DateFormat("MM/dd/yyyy H:mm").parse("6/10/2023 185:00")` evaluates to 2023-06-17 17:00:00.000 which is not something I expected at all...that should error out as an invalid date string.

**Comment by mosuem** [comment]
Without having checked anything, might this be related to the recent whitespace change between `12:00` and `AM` being a narrow non-breaking whitespace?
