### ISSUE TITLE
parsing a string to a DateTime

### ISSUE THREAD

**Issue by aloRanking** [dart-lang/i18n#695]
**Describe the bug**

I was unable to format a string using DateFormat('h:mm a').parse('7:00 PM');
 but this function was working on  0.17.0 version.

i get "FormatException: Trying to read   from 7:00 PM at 5"

**To Reproduce**
Add a minimal working example or, if not possible or available, any code which might help to reproduce the problem
```
try {
 DateTime closingTime = DateFormat('h:mm a').parse();

}  catch (e) {
        debugPrint('$e');
      }
```

**System info**
<The output of `dart pub deps --style compact` in your project>

**Comment by mosuem** [comment]
```dart
import 'package:intl/intl.dart';

void main(List<String> args) {
  DateTime closingTime = DateFormat('h:mm a').parse('7:00 PM');
  print(closingTime);
}

```
Works fine for me locally. Which version are you using? 
Please fill out the 

**System info**
<The output of dart pub deps --style compact in your project>
