### ISSUE TITLE
Cannot get language from package

### ISSUE THREAD

**Issue by vickygaugau** [dart-lang/i18n#699]
Hi everyone, can you help me.

I have a package, and my app include this package
In the package, i have an i18l for multiple language
Ex: I have language, X(key1, key2, key3..) Y(key1, key2, key3)
But when i set locale is Y (i debug and print the current locale is Y), and i call key1, it is return X.key1 (instead of return Y.key1)
(something key is correct, ex: i call key2, it return correctly Y.key2, but i call key1, it is return X.key1)
It just happen in the package
In the parent app is worked ok

Thanks

**Comment by vickygaugau** [comment]
Hi, i have call refresh the page a lot - but sometime it is return correct, sometime it is return fail :(

**Comment by vickygaugau** [comment]
If i set default language (is Y) from pubspec.yaml, it is worked Y ok, but X is not OK :(

**Comment by mosuem** [comment]
Could you include code to reproduce this issue? Please use the bug template to make it easier to understand exactly what the problem is.

**Comment by vickygaugau** [comment]
Hi, i just have been fixed
Because on the file generated - message_all
  initializeInternalMessageLookup(() => new CompositeMessageLookup());
  messageLookup.addLocale(availableLocale, _findGeneratedMessagesFor);
I think it is just only get data from flutter app, not flutter package
I have add more code to resolve my issues
---
  final lookup = CompositeMessageLookup();
  lookup.addLocale(availableLocale, _findGeneratedMessagesFor);
  if (lookup.availableMessages != null &&
      lookup.availableMessages[availableLocale] != null) {
    (messageLookup as CompositeMessageLookup)
        .availableMessages[availableLocale]
        ?.messages
        .addAll(lookup.availableMessages![availableLocale]!.messages);
  }
---
Thanks
