### ISSUE TITLE
Intl Fallback Issue 

### ISSUE THREAD

**Issue by M-A-N-O-J-R** [dart-lang/i18n#714]
**Describe the bug**
intl_es.arb file is loaded for locale es_MX instead of intl_es_MX.arb file 
Country code is not loaded properly

**To Reproduce**
Add a minimal working example or, if not possible or available, any code which might help to reproduce the problem
```
List<Locale> get supportedLocales {
    return const <Locale>[
      Locale.fromSubtags(languageCode: 'en),
      Locale.fromSubtags(languageCode: 'es'),
      Locale.fromSubtags(languageCode: 'es',countryCode:'MX'),
    ];
  }
```

**System info**
<The output of `dart pub deps --style compact` in your project>

**Comment by mosuem** [comment]
This sounds like a Flutter issue, please refile it [there](https://github.com/flutter/flutter/issues/new/choose).
