### ISSUE TITLE
Incorrect Unicode space character in return value from  DateFormat.jms().format(DateTime.now());

### ISSUE THREAD

**Issue by tariqali786** [dart-lang/i18n#717]
The space character immediately preceding "AM"/"PM" in the return value is a Unicode "NARROW NO-BREAK SPACE" (8239) character, instead of the correct "SPACE" (32) character.

var formatTime = DateFormat.jms().format(DateTime.now());

I/flutter ( 9850): formatTime : 11:59:59 AM
I/flutter ( 9850): length: 11
I/flutter ( 9850): char: 49
I/flutter ( 9850): char: 49
I/flutter ( 9850): char: 58
I/flutter ( 9850): char: 53
I/flutter ( 9850): char: 57
I/flutter ( 9850): char: 58
I/flutter ( 9850): char: 53
I/flutter ( 9850): char: 57
**I/flutter ( 9850): char: 8239**   
I/flutter ( 9850): char: 65
I/flutter ( 9850): char: 77

**Comment by mosuem** [comment]
The narrow non-breaking space is the correct character as per the last [CLDR update](https://unicode-org.atlassian.net/browse/CLDR-14032).
