### ISSUE TITLE
Use toLocal() for DateTime field

### ISSUE THREAD

**Issue by lsaudon** [dart-lang/i18n#719]
**Is your feature request related to a problem? Please describe.**
When I use AppLocalizations for a translation with DateTime like `AppLocalizations.of(context).something(DateTime.parse('2023-09-11T11:00:00+02:00'))`, I see the UTC value, but i want the local value.

**Describe the solution you'd like**
By default use `dateTime.toLocal()`; when i generate localization.

Before
```dart
@override
  String time(DateTime dateTime) {
    final intl.DateFormat dateTimeDateFormat = intl.DateFormat('HH\'h\'mm', localeName);
    final String dateTimeString = dateTimeDateFormat.format(dateTime); // <-- HERE

    return '$dateTimeString';
  }
```

After
```dart
@override
  String time(DateTime dateTime) {
    final intl.DateFormat dateTimeDateFormat = intl.DateFormat('HH\'h\'mm', localeName);
    final String dateTimeString = dateTimeDateFormat.format(dateTime.toLocal()); // <-- HERE

    return '$dateTimeString';
  }
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mosuem** [comment]
Per the docs, `DateTime.now()` should already be in your local timezone, so calling `DateTime.now().toLocal()` is a no-op. Or am I missing something?

**Comment by lsaudon** [comment]
Wrong example. It's true.

It don't work with `DateTime.parse('2023-09-11T11:00:00+02:00')`

**Comment by mosuem** [comment]
`DateTime.parse` outputs a `DateTime` in `UTC` if you specify a timezone. So I would factoring out the timezone from the beginning.

Anyhow, as this seems related to Flutter localization and not the `intl_translation` package from this repo, please refile this in the Flutter repo.
