### ISSUE TITLE
DateFormat.jms dose not work in locale zh_CN

### ISSUE THREAD

**Issue by dongfengweixiao** [dart-lang/i18n#724]
**Describe the bug**
DateFormat.jms dose not work in locale zh_CN.

**To Reproduce**
Add a minimal working example or, if not possible or available, any code which might help to reproduce the problem
```
void main(List<String> arguments) {
    DateTime now = DateTime.now();
    S.load(const Locale("zh_CN"));
    debugPrint("zh_CN ${DateFormat.jms().format(now)}");
    S.load(const Locale("zh_HK"));
    debugPrint("zh_HK ${DateFormat.jms().format(now)}");
    S.load(const Locale("zh_TW"));
    debugPrint("zh_TW ${DateFormat.jms().format(now)}");
}

flutter: zh_CN 14:20:33
flutter: zh_HK 下午2:20:33
flutter: zh_TW 下午2:20:33
```

**System info**
Dart SDK 3.1.0
Flutter SDK 3.13.2
dahlia_clock 0.0.1+1

dependencies:
- cupertino_icons 1.0.6
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_riverpod 2.4.0 [collection flutter meta riverpod state_notifier]
- intl 0.18.1 [clock meta path]
- shared_preferences 2.2.1 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_pl
atform_interface shared_preferences_web shared_preferences_windows]
- synchronized 3.1.0

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection m
aterial_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.2
- plugin_platform_interface 2.1.6 [meta]
- riverpod 2.4.0 [meta stack_trace state_notifier]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interf
ace]
- shared_preferences_platform_interface 2.3.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.1 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_in
terface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.1.4-beta
- win32 5.0.7 [ffi]
- xdg_directories 1.0.3 [meta path]

**Comment by mosuem** [comment]
@manishearth I couldn't find the data for the `jms` pattern in the CLDR data to explain this, any hints?

**Comment by mosuem** [comment]
Code to reproduce with Dart:
```
import 'package:intl/date_symbol_data_local.dart';
import 'package:intl/intl.dart';

Future<void> main(List<String> arguments) async {
  DateTime now = DateTime.now();
  await initializeDateFormatting();
  print('zh_CN ${DateFormat.jms('zh_CN').format(now)}');
  print('zh_HK ${DateFormat.jms('zh_HK').format(now)}');
  print('zh_TW ${DateFormat.jms('zh_TW').format(now)}');
}

```

**Comment by Manishearth** [comment]
@mosuem what key does `jms` correspond to?

**Comment by Manishearth** [comment]
Seems like there is?

https://github.com/unicode-org/cldr-json/blob/f93780d69dbd62550cd0a3eb64aa3c73b2c45e91/cldr-json/cldr-dates-full/main/zh/ca-gregorian.json#L367

**Comment by mosuem** [comment]
> @mosuem what key does `jms` correspond to?

The `hour minute second` format I suppose, see [here](https://github.com/unicode-org/cldr/blob/61b74a36de8329daed152005133a699ae7f2012b/tools/cldr-code/src/main/java/org/unicode/cldr/util/DateTimeFormats.java#L402).

> Seems like there is?
> 
> https://github.com/unicode-org/cldr-json/blob/f93780d69dbd62550cd0a3eb64aa3c73b2c45e91/cldr-json/cldr-dates-full/main/zh/ca-gregorian.json#L367

That would be the `hour<sub>24</sub> minute second`, see [here](https://github.com/unicode-org/cldr/blob/61b74a36de8329daed152005133a699ae7f2012b/tools/cldr-code/src/main/java/org/unicode/cldr/util/DateTimeFormats.java#L412C10-L412C52).

I believe `j` is `HOUR`, while `H` is `HOUR24`.


But indeed, comparing https://st.unicode.org/cldr-apps/v#/zh_Hant/Gregorian/header_Formats_Standard_Time_Formats and https://st.unicode.org/cldr-apps/v#/zh/Gregorian/header_Formats_Standard_Time_Formats, this difference is expected.

**Comment by mosuem** [comment]
Yes, this packages data is based on the Unicode CLDR data. If you disagree, file a bug there. Same for the AM/PM markers.

**Comment by Manishearth** [comment]
Yeah I'll file it upstream.

**Comment by Manishearth** [comment]
https://unicode-org.atlassian.net/browse/CLDR-17103

**Comment by Manishearth** [comment]
@mosuem note that CLDR does have patterns for when you explicitly request flexible day periods: https://st.unicode.org/cldr-apps/v#/zh/Gregorian/header_Formats_Flexible_12_Hour_Time_Formats , https://st.unicode.org/cldr-apps/v#/zh_Hant/Gregorian/header_Formats_Flexible_12_Hour_Time_Formats

**Comment by oldherl** [comment]
I'm a zh-CN user and would like to emphasize that we prefer 24-hour than 12-hour notation, even in casual writings. Please do not force us to use 12-hour notation!

**Comment by Manishearth** [comment]
Hold your horses, this issue is not about forcing people into 12hr time :smile:. The CLDR issue was about understanding the situation, this issue is about a _missing_ pattern in Dart which can be fixed a number of ways, one of them being updating CLDR _if that is the correct option to do_. Clearly it isn't!

**Comment by oldherl** [comment]
> What we are currently discussing is that the jms API can be correctly displayed as a 12 hour style in many other locals (not 100% tested), and only displayed as a 24 hour style in zh-cn, which can cause confusion for developers. If you strongly dislike the 12 hour style, it is recommended to always use Hms.
The problem is, many app developers don't give options to choose the format of date/time to users. They use the default format only. As a user, I won't have the option to use 24-hour format if you set the default format to 24-hour for zh-CN locale. 

If the developer feels "confused" by having different time format in different locales, then they should get some knowledge about i18n, instead of forcing all users to use 12-hour format.

**Comment by Manishearth** [comment]
@oldherl these are lower level APIs for when the developer has specific needs

That said, it doesn't seem to me that `j` is "always flexible", it's "whatever the locale prefers", which in this case is h24, so I don't think there's anything to do here. Requesting "always flexible" also seems somewhat off since not every locale supports it. I _suspect_ the current behavior is works as intended.
