### ISSUE TITLE
Invalid parse results with parseStrict when string does not match template

### ISSUE THREAD

**Issue by rumax** [dart-lang/i18n#725]
**Describe the bug**
According to manuals`parseStrict` should 

```
If inputString does not match our format, throws a [FormatException](https://api.flutter.dev/flutter/dart-core/FormatException-class.html). This will reject dates whose values are not strictly valid, even if the DateTime constructor will accept them. It will also reject strings with additional characters (including whitespace) after a valid date
```

So in case of `"dd/mm/yyyy"` template, it should throw exceptions when more or less characters are provided. For example for `"01/01/20235"` (it has 1 extra character for year) it returns `20235-01-01 00:01:00.000` as a result. In case if less characters are provided, `parseStrict("01/01/202")` results in `0202-01-01 00:01:00.000`.

![image](https://github.com/dart-lang/i18n/assets/2707180/4b784a0e-fd48-4cc7-a85f-3ec4f3f1be21)

**To Reproduce**
Add a minimal working example or, if not possible or available, any code which might help to reproduce the problem. Use `dartpad` with:
```
final DateFormat dateFormat = DateFormat("dd/mm/yyyy");
  
  print(dateFormat.parseStrict("01/01/20235"));
  print(dateFormat.parseStrict("01/01/202"));
```

**System info**

https://dartpad.dev/?

**Comment by mosuem** [comment]
`yyyy` does not mean exactly four characters, it is rather an indication to use the "full form", see the [docs](https://github.com/dart-lang/i18n/blob/addMessagesBuilder/pkgs/intl/lib/src/intl/date_format.dart#L187).

**Comment by rumax** [comment]
@mosuem 

So it also should parse

> print(dateFormat.parseStrict("01/01/202358989"));

? 

You can argue of course, but this year will happen one day, same as `20235` which I do not expect for exact match of `yyyy` even if it is in specs.

Additionally you can check other specs, for example https://momentjs.com/docs/#/parsing/ which seems to be more valid

```
YYYY | 2014 | 4 or 2 digit year. Note: Only 4 digit can be parsed on strict mode
```

**Comment by mosuem** [comment]
> So it also should parse
> 
> > print(dateFormat.parseStrict("01/01/202358989"));
> 
> ?

No, as Dart's `DateTime` supports only dates until the year 275760, see the [docs](https://api.dart.dev/stable/3.1.2/dart-core/DateTime-class.html). If you are interested in matching by an exact string, and not a pattern, and your use-case is not locale dependent maybe give the [FixedDateTimeFormatter](https://pub.dev/documentation/convert/latest/convert/FixedDateTimeFormatter-class.html) from `package:convert` a try.

**Comment by rumax** [comment]
Sorry, but I still don't see a use of parsing some input from users today for years up until the year 275760. And where parser gives me invalid dates (20235 or 0202) when I expect 2023. 

But as I mentioned above, there is a link which may inspire you to improvements and see how it is done in other specs, because if I as a consumer give `yyyy` template and use strict parser, **I expect for exactly 4 digits**. In case I need more or less I could use different template like it is defined:

![image](https://github.com/dart-lang/i18n/assets/2707180/c211c13b-e7f8-4050-9281-a4833d7ae14e)

**Comment by mosuem** [comment]
I cannot answer why other libraries or languages such as moment.js do [not follow](http://momentjs.com/docs/#/displaying/format/) the [CLDR convention](https://www.unicode.org/reports/tr35/tr35-dates.html#dfst-year) - but we do not plan to change that.
