### ISSUE TITLE
Incorrect abbreviation formatting on pt_PT language

### ISSUE THREAD

**Issue by amserra** [dart-lang/i18n#741]
**Describe the bug**
Using the default locale as 'pt_PT' (Portugal Portuguese), `ABBR_WEEKDAY` returns the full weekday name (e.g. 'Segunda)'. When using 'pt', or 'pt_BR' (Brazilian Portuguese), the weekday returns as expected (e.g. 'SEG.').

**To Reproduce**
Minimal working example:
```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart';

main() {
  Intl.systemLocale = 'pt_PT';
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [Locale('en'), Locale('pt')],
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          DateFormat(DateFormat.ABBR_WEEKDAY)
              .format(DateTime.now())
              .toUpperCase(),
        ),
      ),
    );
  }
}

```
You can toggle between 'pt_PT', 'pt_BR', and 'pt' to see the difference.

**System info**
Dart SDK 3.1.3
Flutter SDK 3.13.6
test_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- intl 0.18.1 [clock meta path]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- web 0.1.4-beta

**Comment by mosuem** [comment]
This is expected behavior, see https://st.unicode.org/cldr-apps/v#/pt_PT/Gregorian/4e263e689dd6a67e and https://st.unicode.org/cldr-apps/v#/pt/Gregorian/4e263e689dd6a67e.
