### ISSUE TITLE
Wrong DECIMAL_SEP for ru, tr locales

### ISSUE THREAD

**Issue by brand17** [dart-lang/i18n#744]
**Describe the bug**
`NumberFormat.decimalPattern(Platform.localeName).symbols.DECIMAL_SEP` is `,` for the both `ru` and `tr` locales instead of `.`. At the same time `NumberFormat.decimalPattern(Platform.localeName).symbols.DECIMAL_PATTERN` is `#,##0.###`

According to https://st.unicode.org/cldr-apps/v#/ru/Symbols/ the decimal separator is `.` in russian locale. So CLDR data disagree with the library.

**To Reproduce**
Add a minimal working example or, if not possible or available, any code which might help to reproduce the problem
```
void main(List<String> arguments) {
print(NumberFormat.decimalPattern(Platform.localeName).symbols.NAME); // tr
print(NumberFormat.decimalPattern(Platform.localeName).symbols.DECIMAL_SEP); // ,
print(NumberFormat.decimalPattern(Platform.localeName).symbols.DECIMAL_PATTERN); // #,###0.###
}
```

**System info**
Dart SDK 3.1.1
Flutter SDK 3.13.3
from_zero 1.0.0+1

dependencies:
- alt_sms_autofill 1.0.0 [flutter]
- another_flushbar 1.12.30 [flutter]
- async 2.11.0 [collection meta]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- camera 0.10.5+5 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cloud_firestore 4.9.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.17.2
- country_currency_pickers 3.0.0 [flutter]
- cupertino_icons 1.0.6
- currency_picker 2.0.18 [flutter collection]
- device_info_plus 9.1.0 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- dropdown_search 5.0.6 [flutter]
- file_picker 5.5.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 10.5.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.10.1 [firebase_auth_platform_interface 
firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.17.0 [firebase_core_platform_interface 
firebase_core_web flutter meta]
- firebase_messaging 14.6.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface 
firebase_messaging_web flutter meta]
- firebase_storage 11.2.8 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_ui_auth 1.7.0 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations]
- firebase_ui_firestore 1.5.12 [cloud_firestore firebase_ui_localizations flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_app_badger 1.5.0 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_email_sender 6.0.2 [flutter]
- flutter_image_compress 2.0.4 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_stripe 9.4.0 [flutter meta stripe_android stripe_ios stripe_platform_interface]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- forex_conversion 0.2.5+1 [flutter http]
- http 0.13.6 [async http_parser meta]
- intl 0.18.1 [clock meta path]
- latlong2 0.9.0 [intl]
- location 5.0.3 [flutter location_platform_interface location_web]
- mapbox_gl 0.16.0 [flutter mapbox_gl_platform_interface 
mapbox_gl_web collection]
- ntp 2.0.0
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 10.4.5 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_gallery 2.1.1 [flutter]
- pin_code_fields 7.4.0 [flutter]
- provider 6.0.5 [collection flutter nested]
- quiver 3.2.1 [matcher]
- rbush 1.1.1
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sms_autofill 2.3.0 [pin_input_text_field flutter]      
- stripe_ios 9.4.1 [flutter]
- transparent_image 2.0.1
- url_launcher 6.1.14 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]   

transitive dependencies:
- _flutterfire_internals 1.3.7 [collection firebase_core 
firebase_core_platform_interface flutter meta]
- archive 3.4.6 [crypto path pointycastle]
- args 2.4.2
- boolean_selector 2.1.1 [source_span string_scanner]    
- cached_network_image_platform_interface 3.0.0 [flutter 
flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- camera_android 0.10.8+12 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]  
- camera_avfoundation 0.9.13+6 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.5.2 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.2+3 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 5.16.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.7.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+6 [js meta]
- crypto 3.0.3 [typed_data]
- desktop_webview_auth 0.0.12 [crypto flutter http flutter_web_plugins plugin_platform_interface]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- email_validator 2.1.17
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- firebase_analytics_platform_interface 3.7.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+1 [_flutterfire_internals 
firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.19.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links 5.3.7 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.8 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.4.7 [collection firebase_core flutter meta plugin_platform_interface]     
- firebase_storage_web 3.6.8 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]   
- firebase_ui_localizations 1.7.0 [flutter flutter_localizations path]
- firebase_ui_oauth 1.4.10 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.0 [flutter]
- flutter_image_compress_common 1.0.2 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.2 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.3+1 [flutter flutter_web_plugins flutter_image_compress_platform_interface js]   
- flutter_plugin_android_lifecycle 2.0.16 [flutter]      
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 3.3.0 [archive meta xml]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- lints 2.1.1
- location_platform_interface 3.1.2 [flutter plugin_platform_interface]
- location_web 4.2.0 [flutter flutter_web_plugins http_parser js location_platform_interface]
- mapbox_gl_dart 0.2.1 [js]
- mapbox_gl_platform_interface 0.16.0 [flutter meta]     
- mapbox_gl_web 0.16.0 [flutter flutter_web_plugins meta 
mapbox_gl_platform_interface mapbox_gl_dart image]       
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- nested 1.0.0 [flutter]
- octo_image 2.0.0 [flutter]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.0 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.12.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- pin_input_text_field 4.5.1 [flutter]
- platform 3.1.3
- plugin_platform_interface 2.1.6 [meta]
- pointycastle 3.7.3 [collection convert js]
- rxdart 0.27.7
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.4 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.1 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.1 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- stripe_android 9.4.0 [flutter]
- stripe_platform_interface 9.4.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]     
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta 
source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.1.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.7 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.20 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.8 [flutter url_launcher_platform_interface]
- uuid 4.1.0 [crypto sprintf]
- vector_graphics 1.1.9 [flutter vector_graphics_codec]  
- vector_graphics_codec 1.1.9
- vector_graphics_compiler 1.1.9 [args meta path_parsing 
xml vector_graphics_codec path]
- vector_math 2.1.4
- web 0.1.4-beta
- win32 5.0.9 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.3 [meta path]
- xml 6.3.0 [collection meta petitparser]

**Comment by brand17** [comment]
Expected behaviour is `.`, CLDR disagree with the library. I updated the text.

**Comment by brand17** [comment]
I use the following as a workaround now:
```dart
NumberFormat.decimalPattern(Platform.localeName).symbols.DECIMAL_PATTERN[5]
```

**Comment by mosuem** [comment]
The CLDR data specifies a comma as decimal separator for both `ru` and `tr`.
