### ISSUE TITLE
Can named parameters be supported?

### ISSUE THREAD

**Issue by TongCong12138** [dart-lang/i18n#763]
Sometimes, the syntax of different languages is different, resulting in different interpolation orders. For example, in Chinese: "hello": "你好 {firstName} {lastName}", in English: "hello": "hello {lastName} {firstName}". I hope to use S.of (context). hello ({"firstName": "tong", "lastName": "cong"}) in the outside world. How can this be achieved?

**Comment by mosuem** [comment]
As this is a monorepo - for which package is this request?

But this should work out of the box as a feature of `arb` files. Your setup would be something like
`en.arb`
```json
{
 "hello": "Hello {firstName} {lastName}"
}
```

`cn.arb`
```json
{
 "hello": "你好 {lastName} {firstName}"
}
```
