### ISSUE TITLE
Locale for Argentina

### ISSUE THREAD

**Issue by nivlaoh** [dart-lang/i18n#769]
Not an expert in locale here, but I noticed something for the Argentina locale which is different. I'm using intl library in Flutter for currency parsing.

For the Argentina the decimal separator and group separator is denoted as different from the separators declared and used elsewhere.

number_symbols_data.dart
```
"ar": new NumberSymbols(
      NAME: "ar",
      DECIMAL_SEP: '.',
      GROUP_SEP: ',',
```
vs
https://en.wikipedia.org/wiki/Decimal_separator

This is causing an issue with double parsing. Hopefully, someone can shed some light if an override is required on this specific locale instead. Thanks

**Comment by mosuem** [comment]
https://st.unicode.org/cldr-apps/v#/es_AR/Symbols/ seems to agree that those are the correct separators.

Parsing is discouraged in general, as this is very fragile with respect to different [currency formatting patterns](https://st.unicode.org/cldr-apps/v#/es_AR/Number_Formatting_Patterns/). If possible, try to use UI input elements which do not require parsing.
