### ISSUE TITLE
Add support for yMMdd dateformat

### ISSUE THREAD

**Issue by aanelson** [dart-lang/i18n#803]
**Is your feature request related to a problem? Please describe.**

Sometimes dates need a leading zero in the day/month field and the only way to do this is with a custom DateFormat. 
 For example
`final dateFormat = DateFormat('MM/dd/yyyy', locale.toLanguageTag());`

  However, localization does not work correctly if you use a custom date format.

**Describe the solution you'd like**

Add DateFormat.yMMdd()
Add add_MM() and add_dd() methods.

**Describe alternatives you've considered**

static extension on DateFormat for yMMdd, however would have to handle locale mapping.

**Comment by mosuem** [comment]
While `yMd` exists in the [CLDR data](https://st.unicode.org/cldr-apps/v#/en/Gregorian/4af189b39e4e8ddf), `yMMd` does not. So this is not a pattern this package can support.
