### ISSUE TITLE
Merge issue in v1.18.4-2023.2

### ISSUE THREAD

**Issue by Jazzel** [dart-lang/i18n#808]
Error description:
```
ERROR: Failed to generate localization files.
FormatException: Unexpected character (at line 2, character 1)
<<<<<<< HEAD
```
I think someone forgot to fix the merge issue.

**Comment by mosuem** [comment]
Are you sure this is from any package in this repository? [A search](https://github.com/search?q=repo%3Adart-lang%2Fi18n+%2F%28%3F-i%29HEAD%2F&type=code) shows no results.

**Comment by Jazzel** [comment]
I was facing this issue on v1.18.4-2023.2 and when i downgraded it worked fine.

**Comment by mosuem** [comment]
I believe this is not the package with that error, as we also don't have a version `v1.18.4-2023.2`. Please file this bug with the package which is causing this error.
