### ISSUE TITLE
Marathi language support not present

### ISSUE THREAD

**Issue by KartikGavhale** [dart-lang/i18n#865]
**Which locale is missing?**
<e.g. `mr`>

Im trying to traslate my app into marathi , the applocalization_mr.dart file is generated after  adding this property - untranslated-messages-file: untranslated_messages_mr.txt , in i10.yaml , but im not able to change the language , other languages are working fine.

**Comment by badeesAbood** [comment]
could you please provide a sample of your code.

**Comment by KartikGavhale** [comment]
I had found the issue . It is being resolved . Thanks for your attention though
