### ISSUE TITLE
Using intl4x on io platform

### ISSUE THREAD

**Issue by Dan-Crane** [dart-lang/i18n#869]
Hi! Thank you for your work ❤️

Tell me, does `intl4x` work on Android, iOS, Windows? 

I didn't figure out how to connect the package to the project

**Comment by mosuem** [comment]
It should, [here](https://github.com/dart-lang/i18n/releases/tag/intl4x-icu-v.0.9.2-artifacts) is the list of precompiled targets. The build hook of the package should download the right one, and everything should just work(*).

(*) It is currently in experimental, so it might not. Also, there is no treeshaking of the native (i.e. rust) yet, so the binary size might be quite large.

**Comment by Dan-Crane** [comment]
Could you please tell me how to run the build that will launch the hook?

**Comment by mosuem** [comment]
The `hook/build.dart` and `hook/link.dart` scripts are run automatically when running `dart --enable-experiment=native-assets build bin/main.dart`.

**Comment by Dan-Crane** [comment]
@mosuem thanks!)
