### ISSUE TITLE
when i add new word in .arb it dosen't work

### ISSUE THREAD

**Issue by AliSabbar** [dart-lang/i18n#888]
**Describe the bug**
whene i add new word to .arb file and try to use it in ui it not apper in suggestion and i if i typed manually it still give me error 
**The getter 'newLocale' isn't defined for the type 'S'.**
i use the packge flutter intl from vscode to set up my localization in my apps when i run project on flutter version like 3.22.1 it work fine but when i updated to flutter 3.24.2 it won't work any more when i try to run the command in terminal 
`flutter pub global run intl_utils:generate `
it give me error:
![image](https://github.com/user-attachments/assets/1474f0d4-5716-455e-a9a2-c98d203f3765)

**To Reproduce**
usage in UI
```
void main(List<String> arguments) {
print(S.of(context).newLocale)
}
```

**System info**
flutter doctor -v
![image](https://github.com/user-attachments/assets/1a96ed60-1e15-4384-842d-a69c643d9e59)

**Comment by mosuem** [comment]
This seems to belong to package:intl_utils, not here.
