### ISSUE TITLE
Day and Month start with lowercase in Spanish locale 

### ISSUE THREAD

**Issue by yuruyuri16** [dart-lang/i18n#889]
### Steps to reproduce

```dart
final date = DateTime.now();
print(DateFormat.yMMMMEEEEd('es').format(date));
```

### Expected results

```
Jueves, 5 de Septiembre de 2024
```

### Actual results

```
jueves, 5 de septiembre de 2024
```

**Comment by mosuem** [comment]
Have you checked with the template if this is really the expected result?


> Is it really wrong?
> 
> For locale data, there are only a few hard and fast facts, such as the names of days and months. Even these are subject to regional variants, and to changes over time. For example, the “Czech Republic” is known since 2016 as “Czechia”.
> 
> For most of the data, there is no single right answer, but rather a judgment call on what is more customary/appropriate/convenient/whatever.
> 
> Most locale data depends on opinion, preference, and compromise.
> 
> If you do feel strongly that the data is truly wrong, or can be improved significantly, then please report this to [CLDR](http://cldr.unicode.org/index/bug-reports) and not this repository, for which the CLDR data is the source of truth.
