### ISSUE TITLE
Swedish dateformat incorrect in intl 0.19.0

### ISSUE THREAD

**Issue by b055man** [dart-lang/i18n#908]
**Describe the bug**
With the release of intl 0.19.0 some date fomats for Swedish language (sv) got broken.

**To Reproduce**
yMd should result in y-MM-dd, but results in y-M-d instead

**Fix**
The fix is apparently already applied by incorporating CLDR 44.1 months ago (https://github.com/dart-lang/i18n/commit/bbf0259cdff063315a25d41bd08d9b95c94b4c40#diff-10cd4ef15e4657f3982e91855929783d82160498003f224dae18d91abd133104), yet there hasn't been any new version of intl released yet and the last one available is almost 11 months old.
When is a new version expected?

**Comment by mosuem** [comment]
Right, we should publish a new version.
